### ISSUE TITLE
Add an Autoloader

### ISSUE THREAD

**Issue by scottbasgaard** [scottbasgaard/wp-on-board#5]

**Comment by barrykooij** [comment]
![dealwithit](https://cloud.githubusercontent.com/assets/2846594/5790128/4ef08644-9e8a-11e4-9cfe-78e589eed0ba.gif)

**Comment by scottbasgaard** [comment]
Props Trolly
- https://github.com/scottbasgaard/wp-on-board/commit/8672b6fcf11a9eee33fa572c29e6106e1c766c73

**Comment by barrykooij** [comment]
![622](https://cloud.githubusercontent.com/assets/2846594/5793779/e16c8f60-9f50-11e4-8d43-200b335f7b54.gif)
